[package]
name = "data-view"
version = "1.0.0"
edition = "2021"

description = "This library provides a data view for reading and writing data in a byte array."
authors = ["Nur <nurmohammed840@gmail.com>"]
repository = "https://github.com/nurmohammed840/data-view"
license = "Apache-2.0"
keywords = ["lock", "async"]

[features]
BE = []
NE = []

[dependencies]
