name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run clippy
      run: cargo clippy

    - name: Run tests (LE)
      run: cargo test
   
    - name: Run tests (NE)
      run: cargo test --features="NE"

    - name: Run tests (BE)
      run: cargo test --features="BE"